### ISSUE TITLE
[HELP] Problem to set up monkey patch.

### ISSUE THREAD

**Issue by Renan19** [tartpvule/my-firefox-patches#1]
Hey, i am trying to install the monkey path in firefox.

Seted -> general.config.filename to "monkey_Bug1421725_WebRequest.cfg"
Steed -> general.config.sandbox_enabled to false

user_pref("general.config.filename", "monkey_Bug1421725_WebRequest.cfg");
user_pref("general.config.sandbox_enabled", false);

Put monkey_Bug1421725_WebRequest.cfg (Downloaded here) in root Profile Path
put monkey_Bug1421725_WebRequest.cfg  (Downloaded here) in root Firefox path

Dont work! what i am losing?

Firefox Version: 66.0.2
OS: Windows 10

If you can help, thanks!!

**Comment by tartpvule** [comment]
@Renan19 
Have you tried earthlng's suggestions in https://github.com/ghacksuserjs/ghacks-user.js/issues/265#issuecomment-480814847? Namely the part about `autoconfig.js`.

To see if the patch is applied:
1. Go to `about:config`
2. Bring up Scratchpad (Shift+F4)
3. Write `Components.utils.import("resource://gre/modules/WebRequest.jsm", {})`
4. Press `Inspect` button
5. Expand the `HttpObserverManager` property in the right panel
6. If you see `applyChanges2`, the patch is applied successfully.

If the patch is applied but it doesn't appear to be working:
1. Are there WebRequest-related error messages in the Browser Console?
2. Do you have steps to reproduce the issue?

**Comment by Renan19** [comment]
@tartpvule 
Hey, yes, i tried the sugestion. and tryed your test.
Now, its working in firefox lastest version, i can see the applychanges2.
great work, thanks.
