### ISSUE TITLE
monkey_Bug1421725_WebRequest.cfg is broken (have workaround)

### ISSUE THREAD

**Issue by girst** [tartpvule/my-firefox-patches#2]
Hi! I noticed that the monkey-patch version of the WebRequest fix breaks my user agent switcher (looks like it hasn't been kept up to date with the .patch version).

I've found a way to use the  the Bug1421725_WebRequest_central.patch without requiring recompiling firefox and/or repackaging omni.ja. thought I'd share in case it's of any use to you.

1. extract `resource://gre/modules/WebRequest.jsm` and apply the patch (had to do it by hand, as hunk3 didn't apply for me)
2. extract `chrome://extensions/content/parent/ext-webRequest.js`. Near the top, change the path to WR.jsm to `resource://monkey/WebRequest.jsm` (this is the only place WR.jsm is loaded in fx68)
3. place both files in `/usr/lib/firefox/monkey/` (or wherever you've got firefox installed)
4. create a chrome.manifest override to load our files instead:
    	`override chrome://extensions/content/parent/ext-webRequest.js resource://monkey/ext-webRequest.js` (you cannot overwrite resource:// URIs, therefore overriding ext-wr.js)
5. in firefox68, chrome.manifest isn't loaded by default any more. the following autoconfig script loads it again. note that i've renamed it to monkey.manifest so it won't be overwritten by firefox updates.
         `const {FileUtils} = Cu.import('resource://gre/modules/FileUtils.jsm');
         Components.manager.QueryInterface(Ci.nsIComponentRegistrar)
           .autoRegister(FileUtils.getFile('GreD', ['monkey.manifest']));`

**Comment by tartpvule** [comment]
@girst
Thanks for the information about `chrome.manifest`! I didn't know that.
I will probably link to this issue in the next update (after ESR68.1 is released).

> Hi! I noticed that the monkey-patch version of the WebRequest fix breaks my user agent switcher (looks like it hasn't been kept up to date with the .patch version).

How is it breaking? Are there error messages or other hints? What doesn't work? Is it happening in ESR60?

> extract resource://gre/modules/WebRequest.jsm and apply the patch (had to do it by hand, as hunk3 didn't apply for me)

The current `Bug1421725_WebRequest_central.patch` (https://github.com/tartpvule/my-firefox-patches/commit/4dd8c06da18d2137d86ea43a2a4f936b5b100228) was developed on top of https://hg.mozilla.org/mozilla-central/rev/308ef98e6e4b, which was after 68.

When ESR68.1 is released and I switched my build to it, I will update this repo then.

**Comment by girst** [comment]
On Fri, Aug 23, 2019 at 10:48:16PM -0700, tartpvule wrote:
>@girst
>Thanks for the information about `chrome.manifest`! I didn't know that.
>I will probably link to this issue in the next update (after ESR68.1 is released).

Note that the only reason I've done it that way is because I'm already 
using a chrome.manifest for other reasons (see 
https://github.com/girst/legacyfox). I don't know if it's worth it 
otherwise.

>How is it breaking? Are there error messages or other hints? What 
>doesn't work? Is it happening in ESR60?

If only I knew! I noticed days after installing the monkey patch that (I 
think) my user agent faker stopped working. After removing the monkey 
patch (which did correctly merge the CSP headers), the problems 
disappeared. I'm on Fedora's firefox (68 non-ESR), no idea about 60. 

>The current `Bug1421725_WebRequest_central.patch` 
>(https://github.com/tartpvule/my-firefox-patches/commit/4dd8c06da18d2137d86ea43a2a4f936b5b100228) 
>was developed on top of 
>https://hg.mozilla.org/mozilla-central/rev/308ef98e6e4b, which was 
>after 68.

I suspected something like that. Good to know!

**Comment by tartpvule** [comment]
> If only I knew! I noticed days after installing the monkey patch that (I think) my user agent faker stopped working. After removing the monkey patch (which did correctly merge the CSP headers), the problems disappeared. I'm on Fedora's firefox (68 non-ESR), no idea about 60.

Could you point me to the extension or code involved?

**Comment by girst** [comment]
On Fri, Sep 13, 2019 at 11:16:35PM -0700, tartpvule wrote:
>Could you point me to the extension or code involved?

i hope i'm not misrembering which addon i noticed breaking, but this is 
the user agent switcher I'm using (and have been using for quite a 
while): https://gitlab.com/ntninja/user-agent-switcher

again, this is no issue with the updated patch (installed as described 
in this ticket), so I'm not sure if it's worth investigating.

**Comment by tartpvule** [comment]
Hmm, I don't see anything obvious from a cursory reading. May be a subtle problem with the listener from user-agent-switcher returning a Promise (async function) and something is amiss with `await`s in the old `applyChanges1`. That part of the code is a mess.

Given that I have switched over to ESR68.1 with the new `ListenerRunner` class approach, I am probably not going to continue maintaining the old ESR60 version.

That said, if you have the time, can you reproduce the issue with my new `monkey_Bug1421725_WebRequest_esr68.cfg`? (That file is currently a prototype and completely untested, by the way), or a custom-built Firefox with `Bug1421725_WebRequest_esr68_with_308ef98e6e4b.patch`?

**Comment by girst** [comment]
On Sat, Sep 14, 2019 at 08:59:33AM -0700, tartpvule wrote:
>That said, if you have the time, can you reproduce the issue with my 
>new `monkey_Bug1421725_WebRequest_esr68.cfg`? (That file is currently a 
>prototype and completely untested, by the way), or a custom-built 
>Firefox with `Bug1421725_WebRequest_esr68_with_308ef98e6e4b.patch`?

i can test the monkeypatch version in the coming days. (I've given up on 
compiling firefox...too many dependencies I don't want to litter my 
system with and takes ages with fedoras build system, not counting 
running out of memory every other time)

**Comment by girst** [comment]
sorry, took me a while longer to find the time. I've installed the 
monkey patch on my firefox-68.0.2-1.fc29 (appended the .cfg to my 
legacyfox config.js and removed my override)

it successfully merges the headers (test method: dis-, then reenable 
canvasblocker; visit https://gir.st/tmp/javascript.html with js blocked 
in umatrix), and the user agent also works 
(http://www.xhaus.com/headers). 

I'll keep using that new monkeypatch and will report if I notice any 
less obvious breakage (not anticipating it).

since fx69 is out, would you accept patches for it? (not going to 
promise anything, but I'm switching as soon as it gets packaged for 
fedora29)

**Comment by tartpvule** [comment]
@girst
Glad to see that there is no problem and thank you for the testing.
I am closing this issue.

> since fx69 is out, would you accept patches for it? (not going to
promise anything, but I'm switching as soon as it gets packaged for
fedora29)

If you mean accepting a patch into this repo, I am not too sure. I would not be testing any new patches that does not apply to ESR, for instance. My current environment has multiple installations of custom-built ESR68 for Linux and official ESR68 for Windows. Those will be my primary targets. So why not create your own "my firefox patches" repo? I could use a thing or two (like your LegacyFox)!

IMHO, maintaining patches for the release branch with the recently announced faster release cycle is way too much.

P.S. After that stunt in Bugzilla Bug1421725, I am just not motivated to chase after mozilla-central anymore.

**Comment by girst** [comment]
On Tue, Sep 24, 2019 at 11:47:23AM -0700, tartpvule wrote:
>IMHO, maintaining patches for the release branch with the recently 
>announced faster release cycle is way too much.

if only esr was packaged by fedora, I'd stop this madness myself :|

>P.S. After that stunt in Bugzilla Bug1421725, I am just not motivated 
>to chase after mozilla-central anymore.

yeah, that was atrocious.
